"""Export IFC elements into one JSONL record per element.

Records include identity, hierarchy, geometry, and psets split into official
vs custom classifications.
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any

import ifcopenshell
import ifcopenshell.util.element as ifc_element

from rag_tag.parser.ifc43_schema_registry import get_registry
from rag_tag.parser.ifc_geometry_parse import (
    build_geom_settings,
    get_element_bounding_box,
    get_element_centroid,
)
from rag_tag.paths import find_ifc_dir, find_project_root

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

# Bundled ontology map — generated by parse_bsdd_to_map.py
_ONTOLOGY_MAP_PATH = Path(__file__).resolve().parent / "ifc_ontology_map.json"


def _normalize_schema_family(schema_name: str | None) -> str:
    """Normalize IFC schema strings into a stable family label."""
    if not schema_name:
        return "UNKNOWN"
    normalized = schema_name.upper().replace("-", "_")
    if normalized.startswith("IFC4X3"):
        return "IFC4X3"
    if normalized.startswith("IFC4"):
        return "IFC4"
    if normalized.startswith("IFC2X3"):
        return "IFC2X3"
    return normalized


def _load_ontology_map() -> dict:
    """Load class-to-ValidPsets mapping with graceful fallback behavior."""
    if _ONTOLOGY_MAP_PATH.exists():
        try:
            with _ONTOLOGY_MAP_PATH.open(encoding="utf-8") as fh:
                data = json.load(fh)
            logger.info(
                "Loaded ontology map from %s (%d entries)",
                _ONTOLOGY_MAP_PATH,
                len(data),
            )
            return data
        except Exception as exc:
            logger.warning(
                "Failed to read ontology map from %s: %s. "
                "Falling back to in-memory generation.",
                _ONTOLOGY_MAP_PATH,
                exc,
            )

    # NOTE: In-memory fallback keeps conversion offline when bundled data is missing.
    try:
        from rag_tag.parser.parse_bsdd_to_map import build_ontology_map  # noqa: PLC0415

        data = build_ontology_map()
        logger.info("Generated ontology map in-memory (%d entries).", len(data))
        return data
    except Exception as exc:
        logger.warning(
            "Ontology map generation failed: %s. "
            "All psets will be classified as Custom.",
            exc,
        )
        return {}


def _get_valid_psets_for_class(
    canonical_class: str,
    ancestors: list[str],
    ontology_map: dict,
) -> set[str]:
    """Return ValidPsets for a class, falling back through ancestor classes."""
    for cls in [canonical_class, *ancestors]:
        entry = ontology_map.get(cls)
        if entry and isinstance(entry, dict) and "ValidPsets" in entry:
            vp = entry["ValidPsets"]
            if isinstance(vp, list):
                return set(vp)
    return set()


def _to_python(value: Any) -> Any:
    """Convert IFC values into JSON-serializable Python scalars when possible."""
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float, str)):
        return value
    try:
        return float(value)
    except (TypeError, ValueError):
        pass
    try:
        return str(value)
    except Exception:
        return None


def _cast_pset(pset_dict: dict) -> dict:
    """Cast a raw pset mapping and drop the synthetic ``id`` field."""
    return {k: _to_python(v) for k, v in pset_dict.items() if k != "id"}


def _extract_hierarchy(element) -> dict:
    """Extract parent metadata and resolved spatial path for an element."""
    try:
        container = ifc_element.get_container(element)
    except Exception:
        container = None

    parent_id: str | None = None
    parent_type: str | None = None
    level: str | None = None

    if container is not None:
        try:
            gid = getattr(container, "GlobalId", None)
            parent_id = str(gid) if gid else None
        except Exception:
            pass
        try:
            parent_type = container.is_a()
        except Exception:
            pass
        try:
            name = getattr(container, "Name", None)
            level = str(name) if name else None
        except Exception:
            pass

    path: list[str] = []
    try:
        node = container
        while node is not None:
            name = getattr(node, "Name", None)
            if name:
                path.append(str(name))
            node = ifc_element.get_container(node)
        path.reverse()
    except Exception:
        path = []

    return {
        "ParentId": parent_id,
        "ParentType": parent_type,
        "Level": level,
        "Path": path,
    }


def extract_element(
    element,
    ontology_map: dict,
    geom_settings,
    registry,
    *,
    schema_supports_ontology: bool,
) -> dict:
    """Extract one IFC element into the normalized JSONL record schema."""
    try:
        express_id: int | None = element.id()
    except Exception:
        express_id = None

    raw_class = element.is_a()
    norm = registry.normalize_class(raw_class)
    canonical_class = norm.get("canonical", raw_class)

    # NOTE: Unsupported schema families intentionally emit empty BaseClasses.
    ancestors: list[str] = []
    if schema_supports_ontology:
        map_entry = ontology_map.get(canonical_class)
        if isinstance(map_entry, dict):
            map_ancestors = map_entry.get("BaseClasses")
            if isinstance(map_ancestors, list):
                ancestors = [
                    str(item) for item in map_ancestors if isinstance(item, str)
                ]
        if not ancestors:
            ancestors = norm.get("ancestors", [])

    global_id = getattr(element, "GlobalId", None)
    name = getattr(element, "Name", None)
    description = getattr(element, "Description", None)
    object_type = getattr(element, "ObjectType", None)
    tag = getattr(element, "Tag", None)

    predefined_type: str | None = None
    try:
        if hasattr(element, "PredefinedType"):
            pt = element.PredefinedType
            predefined_type = str(pt) if pt else None
    except Exception:
        pass

    type_name: str | None = None
    try:
        obj_type = ifc_element.get_type(element)
        if obj_type and hasattr(obj_type, "Name"):
            n = obj_type.Name
            type_name = str(n) if n else None
    except Exception:
        pass

    hierarchy = _extract_hierarchy(element)

    centroid = get_element_centroid(element, geom_settings)
    bbox = get_element_bounding_box(element, geom_settings)
    geometry = {
        "Centroid": centroid.tolist() if centroid is not None else None,
        "BoundingBox": (
            {"min": bbox[0].tolist(), "max": bbox[1].tolist()}
            if bbox is not None
            else None
        ),
    }

    valid_psets = (
        _get_valid_psets_for_class(canonical_class, ancestors, ontology_map)
        if schema_supports_ontology
        else set()
    )

    official_psets: dict[str, dict] = {}
    custom_psets: dict[str, dict] = {}

    try:
        psets = ifc_element.get_psets(element, psets_only=True)
        for pset_name, pset_data in psets.items():
            if not isinstance(pset_data, dict):
                continue
            cast = _cast_pset(pset_data)
            if pset_name in valid_psets:
                official_psets[pset_name] = cast
            else:
                custom_psets[pset_name] = cast
    except Exception:
        pass

    quantities: dict[str, dict] = {}
    try:
        qtos = ifc_element.get_psets(element, qtos_only=True)
        for qto_name, qto_data in qtos.items():
            if not isinstance(qto_data, dict):
                continue
            quantities[qto_name] = _cast_pset(qto_data)
    except Exception:
        pass

    # NOTE: Keep first-seen order while deduplicating material names.
    materials: list[str] = []
    try:
        raw_mats = ifc_element.get_materials(element)
        seen_mats: set[str] = set()
        for mat in raw_mats:
            try:
                mat_name = getattr(mat, "Name", None)
                if mat_name:
                    mat_str = str(mat_name).strip()
                    if mat_str and mat_str not in seen_mats:
                        seen_mats.add(mat_str)
                        materials.append(mat_str)
            except Exception:
                pass
    except Exception:
        pass

    return {
        "GlobalId": str(global_id) if global_id else None,
        "ExpressId": express_id,
        "Name": str(name) if name else None,
        "IfcType": canonical_class,
        "ClassRaw": raw_class,
        "BaseClasses": ancestors,
        "PredefinedType": predefined_type,
        "Description": str(description) if description else None,
        "ObjectType": str(object_type) if object_type else None,
        "Tag": str(tag) if tag else None,
        "TypeName": type_name,
        "Hierarchy": hierarchy,
        "Geometry": geometry,
        "Materials": materials,
        "PropertySets": {
            "Official": official_psets,
            "Custom": custom_psets,
        },
        "Quantities": quantities,
    }


def convert_ifc_to_jsonl(ifc_path: Path, out_path: Path) -> int:
    """Convert one IFC file to JSONL and return record count."""
    logger.info("Opening %s", ifc_path)
    model = ifcopenshell.open(str(ifc_path))
    schema_version = getattr(model, "schema", "IFC4X3_ADD2")
    logger.info("Schema: %s", schema_version)
    schema_family = _normalize_schema_family(schema_version)
    schema_supports_ontology = schema_family in {"IFC4X3", "IFC4", "IFC2X3"}

    # NOTE: Registry fallback keeps class normalization available for unknown schemas.
    registry = get_registry(schema_name=schema_version)

    if schema_supports_ontology:
        ontology_map = _load_ontology_map()
    else:
        logger.warning(
            "Unsupported schema family '%s' (raw: %s). "
            "Degrading gracefully: all psets -> Custom, BaseClasses -> [].",
            schema_family,
            schema_version,
        )
        ontology_map = {}

    if schema_supports_ontology and not ontology_map:
        logger.warning(
            "Ontology map is empty for schema %s. "
            "All psets will be classified as Custom.",
            schema_version,
        )

    geom_settings = build_geom_settings()
    logger.info("Geometry will be extracted per-element during processing.")

    # NOTE: Spatial roots are not IfcProduct subclasses, so include them explicitly.
    elements: list = list(model.by_type("IfcProduct"))
    for extra in ("IfcProject", "IfcSite", "IfcBuilding"):
        try:
            elements.extend(model.by_type(extra))
        except Exception:
            pass

    # NOTE: IFC4+ can surface duplicates across class queries; dedupe by express id.
    seen: set[int] = set()
    unique: list = []
    for elem in elements:
        eid = elem.id()
        if eid not in seen:
            seen.add(eid)
            unique.append(elem)

    logger.info("Processing %d unique elements...", len(unique))
    out_path.parent.mkdir(parents=True, exist_ok=True)

    count = 0
    with out_path.open("w", encoding="utf-8") as fh:
        for elem in unique:
            try:
                record = extract_element(
                    elem,
                    ontology_map,
                    geom_settings,
                    registry,
                    schema_supports_ontology=schema_supports_ontology,
                )
            except Exception as exc:
                logger.warning("Skipping #%s: %s", elem.id(), exc)
                continue
            fh.write(json.dumps(record, ensure_ascii=False))
            fh.write("\n")
            count += 1

    logger.info("Wrote %d records to %s", count, out_path)
    return count


def main() -> None:
    """Run the IFC-to-JSONL CLI."""
    ap = argparse.ArgumentParser(
        description="Convert IFC file(s) to JSONL (one JSON record per element)."
    )
    ap.add_argument(
        "--ifc-dir",
        type=Path,
        default=None,
        help="Directory containing .ifc files (default: auto-detected IFC-Files/).",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory for .jsonl files (default: <project_root>/output/).",
    )
    ap.add_argument(
        "--ifc-file",
        type=Path,
        default=None,
        help="Single IFC file to convert (overrides --ifc-dir).",
    )
    args = ap.parse_args()

    script_dir = Path(__file__).resolve().parent

    if args.out_dir is not None:
        out_dir = args.out_dir.expanduser().resolve()
    else:
        project_root = find_project_root(script_dir) or script_dir.parent.parent.parent
        out_dir = (project_root / "output").resolve()

    if args.ifc_file is not None:
        ifc_file = args.ifc_file.expanduser().resolve()
        if not ifc_file.is_file():
            print(f"IFC file not found: {ifc_file}")
            return
        out_path = out_dir / (ifc_file.stem + ".jsonl")
        n = convert_ifc_to_jsonl(ifc_file, out_path)
        print(f"\n{ifc_file.name} -> {out_path.name} ({n} elements)")
        return

    if args.ifc_dir is not None:
        ifc_dir = args.ifc_dir.expanduser().resolve()
    else:
        ifc_dir = find_ifc_dir(script_dir)
        if ifc_dir is None:
            print(
                "IFC directory not found. Use --ifc-dir or create an IFC-Files/ folder."
            )
            return

    if not ifc_dir.is_dir():
        print(f"IFC directory not found: {ifc_dir}")
        return

    ifc_files = sorted(f for f in ifc_dir.iterdir() if f.suffix.lower() == ".ifc")
    if not ifc_files:
        print(f"No .ifc files found in {ifc_dir}")
        return

    print(f"Converting {len(ifc_files)} IFC file(s) from {ifc_dir}")
    print(f"Writing JSONL to {out_dir}\n")

    for ifc_path in ifc_files:
        out_path = out_dir / (ifc_path.stem + ".jsonl")
        try:
            n = convert_ifc_to_jsonl(ifc_path, out_path)
            print(f"  {ifc_path.name} -> {out_path.name} ({n} elements)")
        except Exception as exc:
            print(f"  {ifc_path.name} -> ERROR: {exc}")

    print("\nDone.")


if __name__ == "__main__":
    main()
