# reads an IFC file and writes one JSON record per element to a .jsonl file
# each record has the element's identity, where it sits in the building hierarchy,
# its geometry (centroid + bbox), and its property sets split into official vs custom
#
# run with: uv run rag-tag-ifc-to-jsonl

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any

import ifcopenshell
import ifcopenshell.util.element as ifc_element

from rag_tag.parser.ifc43_schema_registry import get_registry
from rag_tag.parser.ifc_geometry_parse import (
    build_geom_settings,
    compute_footprint_polygon_2d,
    compute_oriented_bbox,
    get_element_bounding_box,
    get_element_centroid,
    get_element_local_placement_matrix,
    get_element_mesh,
)
from rag_tag.parser.ifc_relationships import (
    RelationBlock,
    build_relationship_index,
    empty_relation_block,
)
from rag_tag.paths import find_ifc_dir, find_project_root

logger = logging.getLogger(__name__)

# Bundled ontology map — generated by parse_bsdd_to_map.py
_ONTOLOGY_MAP_PATH = Path(__file__).resolve().parent / "ifc_ontology_map.json"


def _normalize_schema_family(schema_name: str | None) -> str:
    """Normalize IFC schema strings into a stable family label."""
    if not schema_name:
        return "UNKNOWN"
    normalized = schema_name.upper().replace("-", "_")
    if normalized.startswith("IFC4X3"):
        return "IFC4X3"
    if normalized.startswith("IFC4"):
        return "IFC4"
    if normalized.startswith("IFC2X3"):
        return "IFC2X3"
    return normalized


def _load_ontology_map() -> dict:
    """
    Load the class-to-ValidPsets mapping from the bundled JSON file.

    Resolution order:
      1. Read ``ifc_ontology_map.json`` next to this module (fastest, offline).
      2. Generate in-memory via ``build_ontology_map()`` (slower, always works
         as long as STANDARD_PSETS is available).
      3. Return an empty dict so the caller degrades gracefully — all psets
         will be classified as Custom rather than crashing.
    """
    if _ONTOLOGY_MAP_PATH.exists():
        try:
            with _ONTOLOGY_MAP_PATH.open(encoding="utf-8") as fh:
                data = json.load(fh)
            logger.info(
                "Loaded ontology map from %s (%d entries)",
                _ONTOLOGY_MAP_PATH,
                len(data),
            )
            return data
        except Exception as exc:
            logger.warning(
                "Failed to read ontology map from %s: %s. "
                "Falling back to in-memory generation.",
                _ONTOLOGY_MAP_PATH,
                exc,
            )

    # Fallback: generate from STANDARD_PSETS in-memory (no RDF needed)
    try:
        from rag_tag.parser.parse_bsdd_to_map import build_ontology_map  # noqa: PLC0415

        data = build_ontology_map()
        logger.info("Generated ontology map in-memory (%d entries).", len(data))
        return data
    except Exception as exc:
        logger.warning(
            "Ontology map generation failed: %s. "
            "All psets will be classified as Custom.",
            exc,
        )
        return {}


def _get_valid_psets_for_class(
    canonical_class: str,
    ancestors: list[str],
    ontology_map: dict,
) -> set[str]:
    """
    Return the set of ValidPsets for an IFC class from the ontology map.

    Checks the canonical class first, then walks the ancestor chain.  This
    ensures that a subclass like IfcWallStandardCase (mapped to IfcWall) still
    finds Pset_WallCommon.

    Returns an empty set when neither the class nor any of its ancestors appears
    in the map — callers then route all psets to Custom (graceful degradation).
    """
    for cls in [canonical_class, *ancestors]:
        entry = ontology_map.get(cls)
        if entry and isinstance(entry, dict) and "ValidPsets" in entry:
            vp = entry["ValidPsets"]
            if isinstance(vp, list):
                return set(vp)
    return set()


def _to_python(value: Any) -> Any:
    # ifcopenshell doesn't always give back plain Python types —
    # sometimes you get enum objects or entity references, so we force cast
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float, str)):
        return value
    try:
        return float(value)
    except (TypeError, ValueError):
        pass
    try:
        return str(value)
    except Exception:
        return None


def _cast_pset(pset_dict: dict) -> dict:
    # ifcopenshell adds an "id" key to every pset dict that we don't want
    return {k: _to_python(v) for k, v in pset_dict.items() if k != "id"}


def _extract_hierarchy(element) -> dict:
    try:
        container = ifc_element.get_container(element)
    except Exception:
        container = None

    parent_id: str | None = None
    parent_type: str | None = None
    level: str | None = None

    if container is not None:
        try:
            gid = getattr(container, "GlobalId", None)
            parent_id = str(gid) if gid else None
        except Exception:
            pass
        try:
            parent_type = container.is_a()
        except Exception:
            pass
        try:
            name = getattr(container, "Name", None)
            level = str(name) if name else None
        except Exception:
            pass

    # walk up the tree to get the full spatial path (e.g. ["building", "floor 1"])
    path: list[str] = []
    try:
        node = container
        while node is not None:
            name = getattr(node, "Name", None)
            if name:
                path.append(str(name))
            node = ifc_element.get_container(node)
        path.reverse()  # we walked bottom-up so flip it
    except Exception:
        path = []

    return {
        "ParentId": parent_id,
        "ParentType": parent_type,
        "Level": level,
        "Path": path,
    }


def extract_element(
    element,
    ontology_map: dict,
    geom_settings,
    registry,
    *,
    schema_supports_ontology: bool,
    relationship_index: dict[str, RelationBlock] | None = None,
) -> dict:
    try:
        express_id: int | None = element.id()
    except Exception:
        express_id = None

    raw_class = element.is_a()
    norm = registry.normalize_class(raw_class)
    canonical_class = norm.get("canonical", raw_class)

    # Prefer ontology-map ancestry when present; otherwise fall back to registry.
    # For unsupported schemas we intentionally degrade: no ontology ancestry.
    ancestors: list[str] = []
    if schema_supports_ontology:
        map_entry = ontology_map.get(canonical_class)
        if isinstance(map_entry, dict):
            map_ancestors = map_entry.get("BaseClasses")
            if isinstance(map_ancestors, list):
                ancestors = [
                    str(item) for item in map_ancestors if isinstance(item, str)
                ]
        if not ancestors:
            ancestors = norm.get("ancestors", [])

    global_id = getattr(element, "GlobalId", None)
    name = getattr(element, "Name", None)
    description = getattr(element, "Description", None)
    object_type = getattr(element, "ObjectType", None)
    tag = getattr(element, "Tag", None)

    predefined_type: str | None = None
    try:
        if hasattr(element, "PredefinedType"):
            pt = element.PredefinedType
            predefined_type = str(pt) if pt else None
    except Exception:
        pass

    type_name: str | None = None
    try:
        obj_type = ifc_element.get_type(element)
        if obj_type and hasattr(obj_type, "Name"):
            n = obj_type.Name
            type_name = str(n) if n else None
    except Exception:
        pass

    hierarchy = _extract_hierarchy(element)

    # Per-element geometry extraction (no model-wide preloading).
    centroid = get_element_centroid(element, geom_settings)
    bbox = get_element_bounding_box(element, geom_settings)
    mesh_vertices, mesh_faces = get_element_mesh(element, geom_settings)
    footprint_poly = compute_footprint_polygon_2d(mesh_vertices)
    oriented_bbox = compute_oriented_bbox(mesh_vertices)
    placement_matrix = get_element_local_placement_matrix(element)
    geometry = {
        "Centroid": centroid.tolist() if centroid is not None else None,
        "BoundingBox": (
            {"min": bbox[0].tolist(), "max": bbox[1].tolist()}
            if bbox is not None
            else None
        ),
        "MeshVertices": (mesh_vertices.tolist() if mesh_vertices is not None else None),
        "MeshFaces": mesh_faces.tolist() if mesh_faces is not None else None,
        "FootprintPolygon2D": (
            footprint_poly.tolist() if footprint_poly is not None else None
        ),
        "LocalPlacementMatrix": (
            placement_matrix.tolist() if placement_matrix is not None else None
        ),
        "OrientedBoundingBox": (
            {
                "center": oriented_bbox["center"].tolist(),
                "axes": oriented_bbox["axes"].tolist(),
                "extents": oriented_bbox["extents"].tolist(),
                "corners_xy": oriented_bbox["corners_xy"].tolist(),
            }
            if oriented_bbox is not None
            else None
        ),
    }

    # Per-class Official/Custom classification: uses each element's own ValidPsets
    # from the ontology map rather than a single global set.  Falls back to empty
    # set (all psets -> Custom) when the class is absent or schema unsupported.
    valid_psets = (
        _get_valid_psets_for_class(canonical_class, ancestors, ontology_map)
        if schema_supports_ontology
        else set()
    )

    official_psets: dict[str, dict] = {}
    custom_psets: dict[str, dict] = {}

    try:
        psets = ifc_element.get_psets(element, psets_only=True)
        for pset_name, pset_data in psets.items():
            if not isinstance(pset_data, dict):
                continue
            cast = _cast_pset(pset_data)
            if pset_name in valid_psets:
                official_psets[pset_name] = cast
            else:
                custom_psets[pset_name] = cast
    except Exception:
        pass

    quantities: dict[str, dict] = {}
    try:
        qtos = ifc_element.get_psets(element, qtos_only=True)
        for qto_name, qto_data in qtos.items():
            if not isinstance(qto_data, dict):
                continue
            quantities[qto_name] = _cast_pset(qto_data)
    except Exception:
        pass

    # Material extraction — uses get_materials which handles all material set
    # types (IfcMaterial, IfcMaterialLayerSet, IfcMaterialConstituentSet, etc.).
    # Deduplicates while preserving order; degrades gracefully on any failure.
    materials: list[str] = []
    try:
        raw_mats = ifc_element.get_materials(element)
        seen_mats: set[str] = set()
        for mat in raw_mats:
            try:
                mat_name = getattr(mat, "Name", None)
                if mat_name:
                    mat_str = str(mat_name).strip()
                    if mat_str and mat_str not in seen_mats:
                        seen_mats.add(mat_str)
                        materials.append(mat_str)
            except Exception:
                pass
    except Exception:
        pass

    # Relationship block — populated from the pre-built index when available.
    # Falls back to an empty block so the key is always present in every record.
    gid_str: str | None = str(global_id) if global_id else None
    relationships: RelationBlock = (
        relationship_index.get(gid_str, empty_relation_block())
        if (relationship_index is not None and gid_str)
        else empty_relation_block()
    )

    return {
        "GlobalId": str(global_id) if global_id else None,
        "ExpressId": express_id,
        "Name": str(name) if name else None,
        "IfcType": canonical_class,
        "ClassRaw": raw_class,
        "BaseClasses": ancestors,
        "PredefinedType": predefined_type,
        "Description": str(description) if description else None,
        "ObjectType": str(object_type) if object_type else None,
        "Tag": str(tag) if tag else None,
        "TypeName": type_name,
        "Hierarchy": hierarchy,
        "Geometry": geometry,
        "Materials": materials,
        "PropertySets": {
            "Official": official_psets,
            "Custom": custom_psets,
        },
        "Quantities": quantities,
        "Relationships": relationships,
    }


def convert_ifc_to_jsonl(ifc_path: Path, out_path: Path) -> int:
    logger.info("Opening %s", ifc_path)
    model = ifcopenshell.open(str(ifc_path))
    schema_version = getattr(model, "schema", "IFC4X3_ADD2")
    logger.info("Schema: %s", schema_version)
    schema_family = _normalize_schema_family(schema_version)
    schema_supports_ontology = schema_family in {"IFC4X3", "IFC4", "IFC2X3"}

    # Registry is schema-aware: hierarchy is built from the detected version.
    # Falls back gracefully when ifcopenshell doesn't recognise the schema string.
    registry = get_registry(schema_name=schema_version)

    # Load per-class pset classification map only for supported schema families.
    # Unknown families degrade gracefully: all psets are treated as Custom and
    # BaseClasses are emitted as empty arrays.
    if schema_supports_ontology:
        ontology_map = _load_ontology_map()
    else:
        logger.warning(
            "Unsupported schema family '%s' (raw: %s). "
            "Degrading gracefully: all psets -> Custom, BaseClasses -> [].",
            schema_family,
            schema_version,
        )
        ontology_map = {}

    if schema_supports_ontology and not ontology_map:
        logger.warning(
            "Ontology map is empty for schema %s. "
            "All psets will be classified as Custom.",
            schema_version,
        )

    # Build geometry settings once; the object is reused for every element.
    geom_settings = build_geom_settings()
    logger.info("Geometry will be extracted per-element during processing.")

    # Build the relationship index in a single pass over the IFC model.
    # This avoids repeated model scans and keeps extract_element() O(1) per element.
    relationship_index = build_relationship_index(model)

    # IfcProduct is the base class for physical building elements (walls, doors, etc.)
    # but IfcProject/IfcSite/IfcBuilding and type objects need explicit inclusion.
    elements: list = list(model.by_type("IfcProduct"))
    for extra in ("IfcProject", "IfcSite", "IfcBuilding", "IfcTypeObject"):
        try:
            elements.extend(model.by_type(extra))
        except Exception:
            pass

    # in IFC4+ some classes show up under both IfcProduct and the spatial types,
    # so deduplicate by express ID before processing
    seen: set[int] = set()
    unique: list = []
    for elem in elements:
        eid = elem.id()
        if eid not in seen:
            seen.add(eid)
            unique.append(elem)

    logger.info("Processing %d unique elements...", len(unique))
    out_path.parent.mkdir(parents=True, exist_ok=True)

    count = 0
    with out_path.open("w", encoding="utf-8") as fh:
        for elem in unique:
            try:
                record = extract_element(
                    elem,
                    ontology_map,
                    geom_settings,
                    registry,
                    schema_supports_ontology=schema_supports_ontology,
                    relationship_index=relationship_index,
                )
            except Exception as exc:
                logger.warning("Skipping #%s: %s", elem.id(), exc)
                continue
            fh.write(json.dumps(record, ensure_ascii=False))
            fh.write("\n")
            count += 1

    logger.info("Wrote %d records to %s", count, out_path)
    return count


def _configure_logging() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")


def main() -> None:
    _configure_logging()
    ap = argparse.ArgumentParser(
        description=(
            "Convert IFC file(s) to JSONL with identity, hierarchy, property sets, "
            "quantities, and geometry blocks including centroid, bounding box, "
            "mesh arrays, and derived geometry when available."
        )
    )
    ap.add_argument(
        "--ifc-dir",
        type=Path,
        default=None,
        help="Directory containing .ifc files (default: auto-detected IFC-Files/).",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory for .jsonl files (default: <project_root>/output/).",
    )
    ap.add_argument(
        "--ifc-file",
        type=Path,
        default=None,
        help="Single IFC file to convert (overrides --ifc-dir).",
    )
    args = ap.parse_args()

    script_dir = Path(__file__).resolve().parent

    if args.out_dir is not None:
        out_dir = args.out_dir.expanduser().resolve()
    else:
        project_root = find_project_root(script_dir) or script_dir.parent.parent.parent
        out_dir = (project_root / "output").resolve()

    if args.ifc_file is not None:
        ifc_file = args.ifc_file.expanduser().resolve()
        if not ifc_file.is_file():
            print(f"IFC file not found: {ifc_file}")
            return
        out_path = out_dir / (ifc_file.stem + ".jsonl")
        n = convert_ifc_to_jsonl(ifc_file, out_path)
        print(f"\n{ifc_file.name} -> {out_path.name} ({n} elements)")
        return

    if args.ifc_dir is not None:
        ifc_dir = args.ifc_dir.expanduser().resolve()
    else:
        ifc_dir = find_ifc_dir(script_dir)
        if ifc_dir is None:
            print(
                "IFC directory not found. Use --ifc-dir or create an IFC-Files/ folder."
            )
            return

    if not ifc_dir.is_dir():
        print(f"IFC directory not found: {ifc_dir}")
        return

    ifc_files = sorted(f for f in ifc_dir.iterdir() if f.suffix.lower() == ".ifc")
    if not ifc_files:
        print(f"No .ifc files found in {ifc_dir}")
        return

    print(f"Converting {len(ifc_files)} IFC file(s) from {ifc_dir}")
    print(f"Writing JSONL to {out_dir}\n")

    for ifc_path in ifc_files:
        out_path = out_dir / (ifc_path.stem + ".jsonl")
        try:
            n = convert_ifc_to_jsonl(ifc_path, out_path)
            print(f"  {ifc_path.name} -> {out_path.name} ({n} elements)")
        except Exception as exc:
            print(f"  {ifc_path.name} -> ERROR: {exc}")

    print("\nDone.")


if __name__ == "__main__":
    main()
